#!/bin/bash

ionic build android --release
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore Lernkartei.keystore platforms/android/build/outputs/apk/android-release-unsigned.apk Lernkartei-release -storepass Lernkartei -keypass Lernkartei 
rm -f build/android-release.apk
/home/marian/Android/Sdk/build-tools/25.0.3/zipalign -v 4 platforms/android/build/outputs/apk/android-release-unsigned.apk build/android-release.apk
rm -f platforms/android/build/outputs/apk/android-release-unsigned.apk